In [1]:
#tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.3.0


In [3]:
#create tensors with tf.constant()
scalar=tf.constant(7)

In [4]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#chech the number of a tensor 
scalar.ndim

0

In [6]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
vector.ndim

1

In [8]:
#create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
#create another matrix
matrix=tf.constant([[10.,7.],[3.,5.],[8.,9.]],dtype=tf.float16)#specify data type
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
matrix.ndim

2

In [12]:
#create another matrix
tensor=tf.constant([[[10.,7.,.4],[3.,5.,9.]],[[8.,9.,.8],[2.,4.,.9]],[[6.,9.,.7],[5.,6.,.7]]])#specify data type
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
tensor.ndim

3

In [14]:
# a scalar a single number 
#Vector  a number with direction
#a matrix is  a 2-demension array of numbers 
# a tensor an n dimensional(dim0,1,2..)
print("ok")

ok


In [15]:
#create  the tensor
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [16]:
#lets try change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#creating random tensors
#random tensors  are tensors of some abitary size which contain random numbers
random1= tf.random.Generator.from_seed(42)#set seed reproducibility
random1= tf.random.normal(shape=(3,2))
random2= tf.random.Generator.from_seed(42)
random2= tf.random.normal(shape=(3,2))
#are they equal
random1,random2,random1==random2

In [ ]:
### shuffle the order of elements in tensor
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
#shuffle our non_shuffled tensor
tf.random.set_seed(42)#global level seed,if both for retain order
tf.random.shuffle(not_shuffled,seed=42)#operation level seed

In [ ]:
##Other ways to tensors
#create a tensor all ones
tf.ones([10,7])

In [ ]:
#create a tensor all zeros
tf.zeros([3,4])

In [ ]:
#you can also use numpy array to tensor
import numpy as np
numpy_a=np.arange(1,25,dtype=np.int32)
numpy_a

In [ ]:
a=tf.constant(numpy_a)
a

In [ ]:
#change dimesion shape
a=tf.constant(numpy_a,shape=(2,3,4))
a

In [ ]:
2*3*4

In [ ]:
a=tf.constant(numpy_a,shape=(3,8))
a

In [ ]:
3*8

In [ ]:
## geting information from tensors
#create 4 rank tensor
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
2*3*4*5

In [ ]:
#get various attributes of our tensor 
print("Datatype of every element ",rank_4_tensor.dtype)
print("Numbers of dimesion(rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("elements alongs 0 th axis",rank_4_tensor.shape[0])
print("elements alongs last axis",rank_4_tensor.shape[-1])
print("elements of tensor",tf.size(rank_4_tensor))

In [ ]:
##tensor can be indexed just like python list
#get a element of each dimension

rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#get  element from each dimesion from each index except final one
rank_4_tensor[:1,:1,:1]

In [ ]:
#create a rank 2 tensor (2 dimension)
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

In [ ]:
rank_2_tensor

In [ ]:
rank_2_tensor[:,-1]

In [ ]:
#add new extra dimension in rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
#alternative  to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)#"-1" mean expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)#"-1" mean expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)#"-1" mean expand the final axis

In [ ]:
#manipulating tensors
#tensor operation
#Basic operation
+,-,*,/


